# Generated by Django 3.2.6 on 2021-10-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='google_oauth_token',
            new_name='google_id_token',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='firstname_jp',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='lastname_jp',
        ),
    ]
